# Generated by Django 5.1.1 on 2024-09-29 02:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0003_recipe_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': '具材', 'verbose_name_plural': '具材一覧'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'レシピ', 'verbose_name_plural': 'レシピ一覧'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(max_length=100, verbose_name='量'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, verbose_name='材料名'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cook.recipe', verbose_name='レシピ'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(verbose_name='レシピの詳細'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='レシピ画像'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=50, verbose_name='レシピ名'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='投稿ユーザー'),
        ),
    ]
