services:
  django:
    build: ./django
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
    expose:
      - 8000:8000
    volumes:
      - ./src:/code
    env_file:
      - ./src/django.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:15.4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./src/db.env
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src/collected_static:/static
      - ./src/media:/media
    depends_on:
      - django
  redis:
    image: redis:latest
    ports:
      - 6379:6379
volumes:
  postgres-data:
